SET client_encoding TO 'UTF8';

\echo '>> 1/7 A exportar Formacoes (Catalogo)...'
\copy (SELECT json_build_object('id_sql', f.id_for, 'nome', f.nome_formacao, 'descricao', f.descricao, 'datas', json_build_object('inicio', f.data_inicio, 'fim', f.data_fim), 'estado', f.estado) FROM bd054_schema.formacoes f) TO 'Ficheiros Migracao/formacoes.json';

\echo '>> 2/7 A exportar Candidatos (com CVs em Base64)...'
\copy (SELECT json_build_object('id_sql', c.id_cand, 'nome', c.nome, 'contactos', json_build_object('email', c.email, 'telemovel', c.telemovel), 'documentos', json_build_object('cv_b64', encode(c.cv, 'base64'), 'carta_motivacao_b64', encode(c.carta_motivacao, 'base64'))) FROM bd054_schema.candidatos c) TO 'Ficheiros Migracao/candidatos.json';

\echo '>> 3/7 A exportar Avaliacoes (agrupadas por funcionario avaliado)...'
\copy (SELECT json_build_object('funcionario_id', id_fun, 'avaliacoes', COALESCE(json_agg(json_build_object('data', data, 'avaliador_id_sql', id_avaliador, 'pontuacao', avaliacao_numerica, 'conteudo', json_build_object('criterios', criterios, 'autoavaliacao', autoavaliacao, 'ficheiro_b64', encode(avaliacao, 'base64'))) ORDER BY data DESC), '[]'::json)) FROM bd054_schema.avaliacoes GROUP BY id_fun) TO 'Ficheiros Migracao/avaliacoes.json';

\echo '>> 4/7 A exportar Vagas (com Candidaturas e Requisitos)...'
\copy (SELECT json_build_object('id_sql', v.id_vaga, 'estado', v.estado, 'data_abertura', v.data_abertura, 'id_depart_sql', v.id_depart, 'requisitos', COALESCE((SELECT json_agg(r.requisito) FROM bd054_schema.requisitos_vaga r WHERE r.id_vaga = v.id_vaga), '[]'::json), 'candidaturas_recebidas', COALESCE((SELECT json_agg(json_build_object('id_candidato_sql', ca.id_cand, 'data', ca.data_cand, 'estado', ca.estado, 'recrutador_id_sql', ca.id_recrutador)) FROM bd054_schema.candidato_a ca WHERE ca.id_vaga = v.id_vaga), '[]'::json)) FROM bd054_schema.vagas v) TO 'Ficheiros Migracao/vagas.json';

\echo '>> 5/7 A exportar Historico Salarial (agrupado por funcionario)...'
\copy (SELECT json_build_object('funcionario_id', id_fun, 'periodos', COALESCE(json_agg(json_build_object('inicio', data_inicio, 'fim', data_fim, 'base', salario_bruto, 'liquido', salario_liquido, 'beneficios', beneficios_array) ORDER BY data_inicio), '[]'::json)) FROM (SELECT r.id_fun, r.data_inicio, r.data_fim, s.salario_bruto, s.salario_liquido, COALESCE((SELECT json_agg(json_build_object('tipo', b.tipo, 'valor', b.valor)) FROM bd054_schema.beneficios b WHERE b.id_fun = r.id_fun AND b.data_inicio = r.data_inicio), '[]'::json) AS beneficios_array FROM bd054_schema.remuneracoes r LEFT JOIN bd054_schema.salario s ON r.id_fun = s.id_fun AND r.data_inicio = s.data_inicio) AS historico GROUP BY id_fun) TO 'Ficheiros Migracao/historico_salarial.json';

\echo '>> 6/7 A exportar Ausencias (agrupadas por funcionario)...'
\copy (SELECT json_build_object('funcionario_id', id_fun, 'ausencias', COALESCE(json_agg(ausencia ORDER BY data_ordenacao), '[]'::json)) FROM (SELECT fe.id_fun, fe.data_inicio AS data_ordenacao, json_build_object('tipo', 'ferias', 'data_inicio', fe.data_inicio, 'data_fim', fe.data_fim, 'num_dias', fe.num_dias, 'estado', fe.estado_aprov) AS ausencia FROM bd054_schema.ferias fe UNION ALL SELECT fa.id_fun, fa.data AS data_ordenacao, json_build_object('tipo', 'falta', 'data', fa.data, 'justificacao', fa.justificacao) AS ausencia FROM bd054_schema.faltas fa) AS todas_ausencias GROUP BY id_fun) TO 'Ficheiros Migracao/ausencias.json';

\echo '>> 7/7 A exportar Funcionarios (documento LEVE com salario atual)...'
\copy (SELECT json_build_object('id_sql', f.id_fun, 'identificacao', json_build_object('nome_completo', f.primeiro_nome || ' ' || f.ultimo_nome, 'nif', f.nif, 'data_nascimento', f.data_nascimento), 'contactos', json_build_object('email', f.email, 'telemovel', f.num_telemovel, 'morada', json_build_object('rua', f.nome_rua, 'localidade', f.nome_localidade, 'cp', f.codigo_postal)), 'info_profissional', json_build_object('cargo', f.cargo, 'departamento', json_build_object('id_depart_sql', d.id_depart, 'nome_depart', d.nome, 'gerente', CASE WHEN d.id_gerente = f.id_fun THEN true ELSE false END)), 'autenticacao', json_build_object('password', (SELECT u.password FROM bd054_schema.utilizadores u WHERE u.id_fun = f.id_fun LIMIT 1), 'permissoes', COALESCE((SELECT json_agg(p.permissao) FROM bd054_schema.permissoes p WHERE p.id_fun = f.id_fun), '[]'::json)), 'dependentes', COALESCE((SELECT json_agg(json_build_object('nome', d2.nome, 'parentesco', d2.parentesco, 'nascimento', d2.data_nascimento)) FROM bd054_schema.dependentes d2 WHERE d2.id_fun = f.id_fun), '[]'::json), 'historico_empresas', COALESCE((SELECT json_agg(json_build_object('empresa', h.nome_empresa, 'cargo', h.cargo, 'inicio', h.data_inicio, 'fim', h.data_fim) ORDER BY h.data_inicio DESC) FROM bd054_schema.historico_empresas h WHERE h.id_fun = f.id_fun), '[]'::json), 'formacoes_realizadas', COALESCE((SELECT json_agg(json_build_object('id_formacao_sql', tf.id_for, 'inicio', tf.data_inicio, 'fim', tf.data_fim)) FROM bd054_schema.teve_formacao tf WHERE tf.id_fun = f.id_fun), '[]'::json), 'salario_atual', (SELECT json_build_object('inicio', r.data_inicio, 'fim', r.data_fim, 'base', s.salario_bruto, 'liquido', s.salario_liquido, 'beneficios', COALESCE((SELECT json_agg(json_build_object('tipo', b.tipo, 'valor', b.valor)) FROM bd054_schema.beneficios b WHERE b.id_fun = r.id_fun AND b.data_inicio = r.data_inicio), '[]'::json)) FROM bd054_schema.remuneracoes r LEFT JOIN bd054_schema.salario s ON r.id_fun = s.id_fun AND r.data_inicio = s.data_inicio WHERE r.id_fun = f.id_fun ORDER BY r.data_inicio DESC LIMIT 1)) FROM bd054_schema.funcionarios f LEFT JOIN bd054_schema.departamentos d ON f.id_depart = d.id_depart) TO 'Ficheiros Migracao/funcionarios.json';