SET client_encoding TO 'UTF8';

\echo '>> 1/6 A exportar Departamentos...'
\copy (SELECT json_build_object('id_sql', d.id_depart, 'nome', d.nome, 'id_gerente_sql', d.id_gerente) FROM bd054_schema.departamentos d) TO 'Ficheiros Migracao/departamentos.json';

\echo '>> 2/6 A exportar Formacoes (Catalogo)...'
\copy (SELECT json_build_object('id_sql', f.id_for, 'nome', f.nome_formacao, 'descricao', f.descricao, 'datas', json_build_object('inicio', f.data_inicio, 'fim', f.data_fim), 'estado', f.estado) FROM bd054_schema.formacoes f) TO 'Ficheiros Migracao/formacoes.json';

\echo '>> 3/6 A exportar Candidatos (com CVs em Base64)...'
\copy (SELECT json_build_object('id_sql', c.id_cand, 'nome', c.nome, 'contactos', json_build_object('email', c.email, 'telemovel', c.telemovel), 'documentos', json_build_object('cv_b64', encode(c.cv, 'base64'), 'carta_motivacao_b64', encode(c.carta_motivacao, 'base64'))) FROM bd054_schema.candidatos c) TO 'Ficheiros Migracao/candidatos.json';

\echo '>> 4/6 A exportar Avaliacoes...'
\copy (SELECT json_build_object('data', a.data, 'avaliado_id_sql', a.id_fun, 'avaliador_id_sql', a.id_avaliador, 'pontuacao', a.avaliacao_numerica, 'conteudo', json_build_object('criterios', a.criterios, 'autoavaliacao', a.autoavaliacao, 'ficheiro_b64', encode(a.avaliacao, 'base64'))) FROM bd054_schema.avaliacoes a) TO 'Ficheiros Migracao/avaliacoes.json';

\echo '>> 5/6 A exportar Vagas (com Candidaturas e Requisitos)...'
\copy (SELECT json_build_object('id_sql', v.id_vaga, 'estado', v.estado, 'data_abertura', v.data_abertura, 'id_depart_sql', v.id_depart, 'requisitos', COALESCE((SELECT json_agg(r.requisito) FROM bd054_schema.requisitos_vaga r WHERE r.id_vaga = v.id_vaga), '[]'::json), 'candidaturas_recebidas', COALESCE((SELECT json_agg(json_build_object('id_candidato_sql', ca.id_cand, 'data', ca.data_cand, 'estado', ca.estado, 'recrutador_id_sql', ca.id_recrutador)) FROM bd054_schema.candidato_a ca WHERE ca.id_vaga = v.id_vaga), '[]'::json)) FROM bd054_schema.vagas v) TO 'Ficheiros Migracao/vagas.json';

\echo '>> 6/6 A exportar O MONSTRO (Funcionarios com TUDO)...'
\copy (SELECT json_build_object('id_sql', f.id_fun, 'identificacao', json_build_object('nome_completo', f.primeiro_nome || ' ' || f.ultimo_nome, 'nif', f.nif, 'data_nascimento', f.data_nascimento), 'contactos', json_build_object('email', f.email, 'telemovel', f.num_telemovel, 'morada', json_build_object('rua', f.nome_rua, 'localidade', f.nome_localidade, 'cp', f.codigo_postal)), 'profissional', json_build_object('cargo', f.cargo, 'id_depart_sql', f.id_depart), 'autenticacao', json_build_object('password', (SELECT u.password FROM bd054_schema.utilizadores u WHERE u.id_fun = f.id_fun LIMIT 1), 'permissoes', COALESCE((SELECT json_agg(p.permissao) FROM bd054_schema.permissoes p WHERE p.id_fun = f.id_fun), '[]'::json)), 'dependentes', COALESCE((SELECT json_agg(json_build_object('nome', d.nome, 'parentesco', d.parentesco, 'nascimento', d.data_nascimento)) FROM bd054_schema.dependentes d WHERE d.id_fun = f.id_fun), '[]'::json), 'historico_empresas', COALESCE((SELECT json_agg(json_build_object('empresa', h.nome_empresa, 'cargo', h.cargo, 'inicio', h.data_inicio, 'fim', h.data_fim)) FROM bd054_schema.historico_empresas h WHERE h.id_fun = f.id_fun), '[]'::json), 'formacoes_realizadas', COALESCE((SELECT json_agg(json_build_object('id_formacao_sql', tf.id_for, 'inicio', tf.data_inicio, 'fim', tf.data_fim)) FROM bd054_schema.teve_formacao tf WHERE tf.id_fun = f.id_fun), '[]'::json), 'registo_ausencias', json_build_object('ferias', COALESCE((SELECT json_agg(json_build_object('inicio', fe.data_inicio, 'fim', fe.data_fim, 'estado', fe.estado_aprov)) FROM bd054_schema.ferias fe WHERE fe.id_fun = f.id_fun), '[]'::json), 'faltas', COALESCE((SELECT json_agg(json_build_object('data', fa.data, 'justificacao', fa.justificacao)) FROM bd054_schema.faltas fa WHERE fa.id_fun = f.id_fun), '[]'::json)), 'historico_salarial', COALESCE((SELECT json_agg(json_build_object('inicio', r.data_inicio, 'fim', r.data_fim, 'base', s.salario_bruto, 'liquido', s.salario_liquido, 'beneficios', COALESCE((SELECT json_agg(json_build_object('tipo', b.tipo, 'valor', b.valor)) FROM bd054_schema.beneficios b WHERE b.id_fun = r.id_fun AND b.data_inicio = r.data_inicio), '[]'::json))) FROM bd054_schema.remuneracoes r LEFT JOIN bd054_schema.salario s ON r.id_fun = s.id_fun AND r.data_inicio = s.data_inicio WHERE r.id_fun = f.id_fun), '[]'::json)) FROM bd054_schema.funcionarios f) TO 'Ficheiros Migracao/funcionarios.json';